name: gazer
channels:
- defaults
dependencies:
- cloudpickle=0.2.2=py34_0
- cython=0.25.2=py34_0
- dask=0.13.0=py34_0
- decorator=4.0.11=py34_0
- dill=0.2.5=py34_0
- h5py=2.6.0=np111py34_2
- jupyter=1.0.0=py34_3
- jupyter_client=4.4.0=py34_0
- jupyter_console=5.0.0=py34_0
- jupyter_core=4.2.1=py34_0
- matplotlib=2.0.0=np111py34_0
- nose=1.3.7=py34_1
- numba=0.30.1=np111py34_0
- numexpr=2.6.1=np111py34_2
- numpy=1.11.3=py34_0
- pandas=0.19.2=np111py34_1
- pickleshare=0.7.4=py34_0
- pillow=4.0.0=py34_0
- pip=9.0.1=py34_1
- python=3.4.5=0
- requests=2.12.4=py34_0
- scikit-image=0.12.3=np111py34_1
- scikit-learn=0.18.1=np111py34_1
- seaborn=0.7.1=py34_0
- six=1.10.0=py34_0
- pip:
  - scipy==0.19.1
  - scikit-optimize==0.3
  - tpot==0.9.1
  - tqdm==4.19.4
  - urllib3==1.22
  - xgboost==0.6

