name: gazer
channels:
- defaults
dependencies:
- cloudpickle=0.2.2
- cython=0.25.2
- decorator=4.0.11
- dill=0.2.5
- h5py=2.6.0
- jupyter=1.0.0
- jupyter_client=4.4.0
- jupyter_console=5.0.0
- jupyter_core=4.2.1
- matplotlib=2.0.0
- nose=1.3.7
- numba=0.30.1
- numexpr=2.6.1
- numpy=1.11.3
- pandas=0.19.2
- pickleshare=0.7.4
- pillow=4.0.0
- pip=9.0.1
- python=3.4.5
- requests=2.12.4
- scikit-image=0.12.3
- scikit-learn=0.18.1
- seaborn=0.7.1
- six=1.10.0
- pip:
  - scipy==0.19.1
  - scikit-optimize==0.3
  - tpot==0.9.1
  - tqdm==4.19.4
  - urllib3==1.22
  - xgboost==0.6
  - keras==2.15
